---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install database-server softwares
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
  sudo: yes

- name: Adds Python MySQL support on Ubuntu
  apt: pkg="python-mysqldb" state=present
  sudo: yes

- name: Install python-pip
  apt: pkg="python-pip" state=present
  sudo: yes

- name: Install PyMySQL
  command: pip install PyMySQL
  sudo: yes

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  sudo: yes

- name: Create mysql user
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL
  sudo: yes
