---
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install server softwares
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - mariadb-server
    - php
    - php-mysql
    - libapache2-mod-php
    - python-mysqldb
