---
# tasks file for php
- name: Install php extensions
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - php-curl
    - php-gd
    - php-mbstring
    - php-xml
    - php-xmlrpc
    - php-soap
    - php-intl
    - php-zip
